# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19u9HIHG6rnjQWOLD81pwSLGWdPWFET0F
"""

import os
import ipywidgets as widgets
from IPython.display import display, clear_output

PASSWORD_FILE = "passwords.txt"

def hash_password(password):
    return password[::-1]

def read_passwords():
    passwords = {}
    if os.path.exists(PASSWORD_FILE):
        with open(PASSWORD_FILE, 'r') as f:
            for line in f:
                username, hashed_password = line.strip().split(' ')
                passwords[username] = hashed_password
    return passwords

def write_passwords(passwords):
    with open(PASSWORD_FILE, 'w') as f:
        for username, hashed_password in passwords.items():
            f.write(f"{username} {hashed_password}\n")

# UI elements
username_input = widgets.Text(placeholder="Enter username", description="Username:")
password_input = widgets.Password(placeholder="Enter password", description="Password:")
output = widgets.Output()

def add_password(b):
    with output:
        clear_output()
        username = username_input.value.strip()
        password = password_input.value.strip()
        if username and password:
            passwords = read_passwords()
            if username in passwords:
                print("Error: Username already exists!")
            else:
                passwords[username] = hash_password(password)
                write_passwords(passwords)
                print("Success: Password added!")
        else:
            print("Error: Please enter both username and password.")

def get_password(b):
    with output:
        clear_output()
        username = username_input.value.strip()
        if username:
            passwords = read_passwords()
            if username in passwords:
                print(f"Password for {username}: {passwords[username][::-1]}")
            else:
                print("Error: Username not found!")
        else:
            print("Error: Please enter a username!")

def list_passwords(b):
    with output:
        clear_output()
        passwords = read_passwords()
        if passwords:
            for user, pwd in passwords.items():
                print(f"{user}: {pwd[::-1]}")
        else:
            print("No passwords saved!")

def delete_password(b):
    with output:
        clear_output()
        username = username_input.value.strip()
        if username:
            passwords = read_passwords()
            if username in passwords:
                del passwords[username]
                write_passwords(passwords)
                print(f"Success: Deleted password for {username}")
            else:
                print("Error: Username not found!")
        else:
            print("Error: Please enter a username!")

# Buttons
add_button = widgets.Button(description="Add Password")
get_button = widgets.Button(description="Get Password")
list_button = widgets.Button(description="List All Passwords")
delete_button = widgets.Button(description="Delete Password")

add_button.on_click(add_password)
get_button.on_click(get_password)
list_button.on_click(list_passwords)
delete_button.on_click(delete_password)

# Display the UI
display(username_input, password_input, add_button, get_button, list_button, delete_button, output)